Repository ahmadalwi425/hackShop, pull requests merged in 2020-10, with the labels that each got.

#3 menambahkan notifikasi untuk setiap proses
  asset/tool.php
  employee/destroy.php
  employee/store.php
  employee/update.php
  item/destroy.php
  item/store.php
  item/updateItem.php
  login/cek.php
  login/login.php
  login/logout.php
  login/sessionlogout.php
Labels: hacktoberfest-accepted

#4 Memperbaiki bug pada notifikasi login dan navbar logout
  asset/js/jquery-3.5.1.slim.min.js
  asset/tool.php
Labels: bug, hacktoberfest-accepted

#5 Perbaikan Header,tapi activenya tetep ga bisa
  asset/css/style.css
  asset/tool.php
Labels: hacktoberfest-accepted

#6 Menambahkan filter saat gagal login dan judul page
  asset/tool.php
  employee/add.php
  employee/destroy.php
  employee/edit.php
  employee/index.php
  employee/store.php
  employee/title.php
  employee/update.php
  item/addItem.php
  item/editItem.php
  item/index.php
  item/store.php
  item/title.php
  item/updateItem.php
  item/userItem.php
  login/cek.php
  login/logout.php
Labels: enhancement, hacktoberfest-accepted

#7 memperbaiki bug navbar
  asset/tool.php
  item/index.php
Labels: hacktoberfest-accepted
